"""RatingPredictor: a locally-trained scikit-learn regressor that predicts
the Rating a user would likely give an unrated Song (Ticket 5).

Design choices (documented here since SPEC.md calls the exact feature/model
choice "not load-bearing" -- keep it simple, keep it honest):

Synthetic bootstrap heuristic
------------------------------
Real Ratings are sparse, especially early on, so every training call always
includes a synthetic bootstrap dataset generated by ``generate_synthetic_dataset``.
This is NOT real taste data -- it is a made-up heuristic rule used purely so
the regressor has *something* to fit before the user has rated anything:

    synthetic_rating = 2.5
                       + 0.25 * (energy - 5)          # higher energy -> higher rating
                       + 0.75 if genre in PREFERRED_GENRES else 0
                       + 0.3 * |tags ∩ PREFERRED_TAGS|
                       + gaussian noise (mean 0, stdev 0.4)
                       clipped to [1.0, 5.0]

``PREFERRED_GENRES`` and ``PREFERRED_TAGS`` are arbitrary stand-ins for "a
taste profile" -- there is no claim this reflects any real user. The noise
term keeps the dataset from being a perfectly learnable linear function (a
regressor that fits it exactly would be overfitting a toy rule, not learning
taste). Generation is deterministic given a seed: a fresh ``random.Random(seed)``
is created per call, so calling the function twice with the same seed
produces byte-identical output -- important for reproducible tests/grading.

Feature extraction
-------------------
``extract_features(song)`` turns a Song dict into a fixed-length numeric
vector, derived only from fields real Songs already carry (energy, genre,
tags):

    [energy]
    + one-hot over GENRE_VOCAB (8 slots)
    + 1 "other genre" flag (genre not in GENRE_VOCAB)
    + one-hot presence over TAG_VOCAB (10 slots, order-independent)
    + count of tags outside TAG_VOCAB

Total length: 1 + 8 + 1 + 10 + 1 = 21. This is intentionally simple (no
hashing trick, no embeddings) -- it just needs to be deterministic and give
the regressor *some* signal to work with.

Model choice
------------
``LinearRegression`` (scikit-learn). Chosen over a tree for three reasons:
it's fast and fully deterministic (no random splits to seed), it supports
``sample_weight`` directly in ``fit()``, and it's simple enough that a
one-line docstring explanation is honest about what it's doing. The
``sample_weight`` support is what makes the "real ratings measurably move
the prediction" requirement practical: real (song, rating) pairs are always
sparse relative to the ~200-row synthetic bootstrap set, so each real rating
is given a much higher fit weight (``REAL_RATING_WEIGHT``) than each
synthetic row. Without that weighting, a handful of real ratings would be
statistically drowned out by the synthetic rows and the model's output
would barely move -- defeating the point of learning from real Ratings at
all.
"""

import random
from dataclasses import dataclass
from typing import Dict, List

from sklearn.linear_model import LinearRegression

import ratings as ratings_module
from playlist_logic import Song

# --- Fixed vocabularies for feature extraction (documented above) ---------

GENRE_VOCAB = ["rock", "lofi", "electronic", "pop", "jazz", "classical", "hiphop", "country"]

TAG_VOCAB = [
    "classic",
    "guitar",
    "study",
    "synth",
    "chill",
    "party",
    "acoustic",
    "live",
    "dance",
    "sad",
]

# --- Synthetic bootstrap heuristic constants -------------------------------

PREFERRED_GENRES = {"rock", "electronic"}
PREFERRED_TAGS = {"guitar", "synth", "party"}

# How much more a single real rating counts than a single synthetic row when
# fitting the regressor. See "Model choice" in the module docstring.
REAL_RATING_WEIGHT = 20.0

# Fallback naive-baseline prediction when there are zero real ratings to
# average -- the exact midpoint of the 1-5 star scale.
NAIVE_BASELINE_FALLBACK = 3.0


def extract_features(song: Song) -> List[float]:
    """Turn a Song dict into the fixed 21-element numeric feature vector
    documented in this module's docstring. Deterministic: same song in,
    same vector out, every time.
    """
    energy = float(song.get("energy", 0))
    genre = str(song.get("genre", "")).strip().lower()
    tags = {str(t).strip().lower() for t in song.get("tags", []) or []}

    genre_one_hot = [1.0 if genre == g else 0.0 for g in GENRE_VOCAB]
    other_genre_flag = [0.0 if genre in GENRE_VOCAB else 1.0]
    tag_one_hot = [1.0 if t in tags else 0.0 for t in TAG_VOCAB]
    other_tag_count = [float(len(tags - set(TAG_VOCAB)))]

    return [energy] + genre_one_hot + other_genre_flag + tag_one_hot + other_tag_count


def _heuristic_rating(song: Song, rng: random.Random) -> float:
    """The synthetic taste rule described in the module docstring."""
    energy = float(song.get("energy", 0))
    genre = str(song.get("genre", "")).strip().lower()
    tags = {str(t).strip().lower() for t in song.get("tags", []) or []}

    rating = 2.5
    rating += 0.25 * (energy - 5)
    if genre in PREFERRED_GENRES:
        rating += 0.75
    rating += 0.3 * len(tags & PREFERRED_TAGS)
    rating += rng.gauss(0, 0.4)

    return max(1.0, min(5.0, rating))


def generate_synthetic_dataset(n_samples: int = 200, seed: int = 42) -> List[dict]:
    """Generate a deterministic synthetic bootstrap dataset of
    ``{"song": Song-like dict, "rating": float}`` entries using the
    heuristic taste rule documented in this module's docstring.

    This is a bootstrap stand-in for real taste data, not a claim about any
    actual user's preferences. A fresh ``random.Random(seed)`` is created on
    every call, so ``generate_synthetic_dataset(seed=42)`` called twice
    produces identical output -- required for reproducible tests/grading.
    """
    rng = random.Random(seed)
    dataset = []
    all_tags = TAG_VOCAB
    for i in range(n_samples):
        energy = round(rng.uniform(0, 10), 2)
        genre = rng.choice(GENRE_VOCAB + ["other"])
        n_tags = rng.randint(0, 3)
        tags = rng.sample(all_tags, n_tags) if n_tags else []
        song = {
            "title": f"synthetic_song_{i}",
            "artist": f"synthetic_artist_{i}",
            "genre": genre,
            "energy": energy,
            "tags": tags,
        }
        rating = _heuristic_rating(song, rng)
        dataset.append({"song": song, "rating": rating})
    return dataset


@dataclass
class RatingPredictorModel:
    """A fitted RatingPredictor: pairs a scikit-learn regressor with the
    feature extraction it was trained on (``extract_features``, module-level
    and stateless, so it's implicit rather than stored per-instance).
    """

    estimator: LinearRegression

    def predict_one(self, song: Song) -> float:
        features = extract_features(song)
        return float(self.estimator.predict([features])[0])


def train(
    songs: List[Song],
    ratings: Dict[str, int],
    synthetic_n: int = 200,
    seed: int = 42,
) -> RatingPredictorModel:
    """Train a RatingPredictor.

    Always includes the synthetic bootstrap dataset (``generate_synthetic_dataset``).
    Additionally incorporates any real ratings found in ``ratings`` (the same
    song_key -> stars shape ``ratings.all_ratings()`` returns) by matching
    each song in ``songs`` against ``ratings`` via ``ratings.song_key`` --
    reusing that exact normalization rather than re-deriving key logic here,
    per ratings.py's own docstring guidance.

    Real (song, rating) pairs are fit with ``REAL_RATING_WEIGHT`` times the
    weight of a synthetic row, so a handful of real ratings can measurably
    shift predictions even against a much larger synthetic set. See the
    "Model choice" section of this module's docstring for why.
    """
    synthetic = generate_synthetic_dataset(n_samples=synthetic_n, seed=seed)
    X: List[List[float]] = [extract_features(row["song"]) for row in synthetic]
    y: List[float] = [row["rating"] for row in synthetic]
    sample_weight: List[float] = [1.0] * len(synthetic)

    for song in songs:
        key = ratings_module.song_key(song)
        if key in ratings:
            X.append(extract_features(song))
            y.append(float(ratings[key]))
            sample_weight.append(REAL_RATING_WEIGHT)

    estimator = LinearRegression()
    estimator.fit(X, y, sample_weight=sample_weight)
    return RatingPredictorModel(estimator=estimator)


def predict(model: RatingPredictorModel, song: Song) -> float:
    """Predict the rating ``song`` would likely receive, using ``model``.

    Returned as a float on the 1-5 scale (not rounded/clamped to an int) --
    this is an internal scoring signal for the future RecommendationAgent,
    not a value shown directly to users.
    """
    return model.predict_one(song)


def naive_baseline_predict(songs: List[Song], ratings: Dict[str, int]) -> float:
    """Trivial baseline for before/after comparison: the plain average of
    all real ratings in ``ratings``, or ``NAIVE_BASELINE_FALLBACK`` (3.0,
    the midpoint of the 1-5 scale) if there are none.

    ``songs`` is accepted but unused -- kept for interface symmetry with
    ``train()`` so callers can pass the same two arguments to both, and to
    leave room for a future per-song-aware baseline without changing the
    signature.
    """
    del songs  # intentionally unused, see docstring
    if not ratings:
        return NAIVE_BASELINE_FALLBACK
    return sum(ratings.values()) / len(ratings)
